language: rust
sudo: 9000
rust:
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
