[package]

name = "js"
version = "0.1.1"
authors = ["The Servo Project Developers"]

build = "build.rs"

[features]
debugmozjs = ['mozjs_sys/debugmozjs']

[dependencies.mozjs_sys]
git = "https://github.com/servo/mozjs"

[dependencies]
libc = "0.2"
rustc-serialize = "0.3"
log = "0.3"
heapsize = "0.1.1"
num = "0.1.24"
